# Generated by Django 5.0.7 on 2024-08-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventrories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=60)),
                ('capacity', models.CharField(max_length=60)),
                ('locaction', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('quantity', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('invname', models.CharField(max_length=60)),
            ],
        ),
    ]
