# Generated by Django 5.0.7 on 2024-08-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventrories',
            old_name='names',
            new_name='name',
        ),
    ]
