# Generated by Django 5.0.7 on 2024-08-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0002_rename_names_inventrories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventrories',
            old_name='locaction',
            new_name='location',
        ),
    ]
