# Generated by Django 5.0.7 on 2024-08-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0003_rename_locaction_inventrories_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventrories',
            new_name='Inventories',
        ),
    ]
